baseURL = "https://aswinmohan.me/"
languageCode = "en-us"
title = "aswinmohanme"
theme = "hugo-ink"
paginate = 8

copyright = "Â© Copyright Aswin Mohan"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-123-45"
disqusShortname = "ink-demo"

[params]
	subtitle = "rants of someone interested in code, design and life."

	# Optional 64x64 avatar image.
	avatar = "https://avatars.io/twitter/aswinmohanme"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	# mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/aswinmohanme"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/aswinmohanme"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
